modLoader="javafml"
loaderVersion="[2,)"
license="CoFH \"Don't Be a Jerk\" License"

[[mods]]
	modId="draconicevolution"
	displayName="Draconic Evolution"
	version="${file.jarVersion}"
	authors="brandon3055"
	description=''''''
	updateJSONURL="https://version-check.covers1624.net/check/?mod=Draconic-Evolution&mc=${mc_version}"

[[dependencies.draconicevolution]]
	modId="neoforge"
	type="required"
	versionRange="[${neo_version},)"
	ordering="NONE"
	side="BOTH"
[[dependencies.draconicevolution]]
	modId="minecraft"
	type="required"
	versionRange="[1.20.4]"
	ordering="NONE"
	side="BOTH"
[[dependencies.draconicevolution]]
    modId="computercraft"
	type="optional"
    versionRange="[${cct_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.draconicevolution]]
	modId="codechickenlib"
	type="required"
	versionRange="${ccl_version}"
	ordering="NONE"
	side="BOTH"
[[dependencies.draconicevolution]]
	modId="brandonscore"
	type="required"
	versionRange="[${bcore_version},)"
	ordering="AFTER"
	side="BOTH"

